services:
  api:
    build:
      context: .
      dockerfile: .docker/dev.Dockerfile
    ports:
      - 3000:3000

    environment:
      DB_CONN: mongodb+srv://user:MuqGq1bA8vbLCUWI@testchat.tua47.mongodb.net/?retryWrites=true&w=majority&appName=testchat
      # DB_CONN: mongodb://user:jG5gbDx9!g@db/

    env_file:
      - .env

  #   depends_on:
  #     - db
  # db:
  #   image: mongo:latest
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: user
  #     MONGO_INITDB_ROOT_PASSWORD: jG5gbDx9!g
