GET http://localhost:3000/api/messages
Cookie: session=MGRiM2Y3OTItYjY1ZS00YzZkLTk2MTMtNWRlYjcyMGYwM2E3MjAyNC0xMi0xNiAyMzozMzowMy43MzIyODg3MDIgKzAwMDAgVVRDIG09KzQ1Ljg1NjEwMTMwMQ==ZzRGOUJEYm4=; Domain=localhost; HttpOnly
