GET http://localhost:5173/api/messages
Cookie: session=OTFiMmViZWEtNzhmMC00YmYyLWI0ZDEtZjg2NGQyMjhiYjk2MjAyNC0xMi0xNiAyMjoyNToyOC4yNDAyMTc4MTQgKzAwMDAgVVRDIG09KzU0My4wNzIyMzI2ODk=MmNJNG42c00=; Domain=localhost; HttpOnly
