GET http://localhost:5173/api/session
Cookie: session=ZTVkN2YyOGYtNjgzNC00MDdmLThjODMtMDFjYTZlYjkxMWZkMjAyNC0xMi0xNyAxMzo0NToyNy40MzU4ODE5MzggKzAwMDAgVVRDIG09KzIxLjI4NzI3NjYwMQ==MG1qVXZWZDI=; Domain=localhost; HttpOnly
