services:
  chatapp:
    image: ghcr.io/barealek/chatapp:0.2
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: jG5gbDx9!g
    volumes:
      - data:/data/db

  cf:
    image: cloudflare/cloudflared:latest
    env_file:
      - .env
    command: tunnel run

volumes:
  data:
    driver_opts:
      type: none
      o: bind
      device: /data/chatapp
